=== naikiki87/sieve2/Server/tasks/dist/config/task.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/task.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE task-list SYSTEM "task.dtd">

    <task-list>
    ...
    </task-list>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT task-list (task|algorithm-definition)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT algorithm-definition (algorithm-identifier)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT algorithm-identifier EMPTY>
<!ATTLIST algorithm-identifier
    name CDATA #IMPLIED
    mode CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT task (job-mapping-list|job-list|cost_catalog|query-list|visible-other-user|description|creation-date|owner|name)*>
<!ATTLIST task
    mode CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT owner (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT creation-date (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT description (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT visible-other-user (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT query-list (query)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT query (ActuatorCondition|Description|SQLStatement|sql)*>
<!ATTLIST query
    type CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sql (conditions|sources|columns)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT columns (column)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT column EMPTY>
<!ATTLIST column
    query CDATA #IMPLIED
    stream CDATA #IMPLIED
    attribute CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT sources (source)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT source EMPTY>
<!ATTLIST source
    query CDATA #IMPLIED
    window CDATA #IMPLIED
    type CDATA #IMPLIED
    stream CDATA #IMPLIED
    data-definition-id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT conditions (joins|selections)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT selections (selection)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT selection EMPTY>
<!ATTLIST selection
    query CDATA #IMPLIED
    var CDATA #IMPLIED
    stream CDATA #IMPLIED
    operation CDATA #IMPLIED
    attribute CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT joins EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT SQLStatement (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Description EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ActuatorCondition EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cost_catalog (history|join-list|attribute-list|stream-list|monitoring)*>
<!ATTLIST cost_catalog
    task_id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT monitoring EMPTY>
<!ATTLIST monitoring
    count CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT stream-list EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT attribute-list EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT join-list EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT history EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT job-list (job)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT job (export-list|property-result-graph-setting-list|parameter-list|input-queue-size|description|name)*>
<!ATTLIST job
    pos_y CDATA #IMPLIED
    pos_x CDATA #IMPLIED
    pos_index CDATA #IMPLIED
    identifier CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT input-queue-size (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT parameter-list (column|condition|output-queue-list|selection|number-of-blank|pipe-name|data-definition-id|source)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT data-definition-id (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT pipe-name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT number-of-blank (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT property-result-graph-setting-list EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT export-list EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT output-queue-list (queue)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT queue EMPTY>
<!ATTLIST queue
    id CDATA #IMPLIED
    bitmap CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT condition (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT job-mapping-list (mapping)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT mapping (child-job)*>
<!ATTLIST mapping
    parent-id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT child-job EMPTY>
<!ATTLIST child-job
    id CDATA #IMPLIED
  >

=== naikiki87/sieve2/Server/sieveXML/task.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE task-list SYSTEM "task.dtd">
<task-list>
<algorithm-definition>
<algorithm-identifier id="1" mode="common" name="dblab.common.job.basestream.DefaultBasestream"/>
<algorithm-identifier id="2" mode="common" name="dblab.common.job.selectio.DefaultSelection"/>
<algorithm-identifier id="3" mode="mining" name="dblab.dsmm.job.estDec.EstDec"/>
<algorithm-identifier id="4" mode="mining" name="Sequence"/>
<algorithm-identifier id="5" mode="mining" name="Association"/>
<algorithm-identifier id="6" mode="common" name="dblab.common.job.Transactionalizer.Transactionalizer"/>
<algorithm-identifier id="7" mode="common" name="dblab.common.job.projection.Projection"/>
<algorithm-identifier id="8" mode="common" name="dblab.common.job.split.Split"/>
<algorithm-identifier id="9" mode="mining" name="dblab.dsmm.job.siblinglist.ClusteringOneDimension"/>
<algorithm-identifier id="10" mode="mining" name="dblab.dsmm.job.cstree.ClusteringFullDimension"/>
<algorithm-identifier id="101" mode="mining" name="dblab.dsmm.job.sttree.ClusteringSubDimension"/>
<algorithm-identifier id="11" mode="common" name="dblab.dsms.job.selection.BitSelection"/>
<algorithm-identifier id="12" mode="common" name="dblab.common.job.join.Bjoin"/>
<algorithm-identifier id="13" mode="common" name="dblab.common.job.join.MJoin"/>
<algorithm-identifier id="14" mode="common" name="dblab.common.job.alisa[pane]"/>
<algorithm-identifier id="15" mode="query processing" name="dblab.dsms.job.finaljob.Final"/>
<algorithm-identifier id="16" mode="query processing" name="dblab.dsms.job.analysis.Analysis"/>
<algorithm-identifier id="20" mode="olap" name="dblab.olap.job.myOlap.MyOlap"/>
<algorithm-identifier id="21" mode="common" name="dblab.common.job.alisa[multiplepane]"/>
<algorithm-identifier id="22" mode="mining" name="dblab.dsmm.job.topk.TopK"/>
<algorithm-identifier id="23" mode="mining" name="dblab.dsmm.job.estDec.EstDec64"/>
<algorithm-identifier id="24" mode="common" name="dblab.common.job.Union.Union"/>
<algorithm-identifier id="25" mode="mining" name="dblab.dsmm.job.ctxrule.ContextRule"/>
<algorithm-identifier id="26" mode="mining" name="dblab.dsmm.job.ctxseq.ContextSeq"/>
<algorithm-identifier id="27" mode="common" name="dblab.dsmm.job.velocity.Velocity"/>
<algorithm-identifier id="28" mode="common" name="dblab.common.job.mergeJob.MergeJob"/>
<algorithm-identifier id="29" mode="common" name="dblab.common.job.expression.ExpressionJob"/>
<algorithm-identifier id="30" mode="common" name="dblab.common.job.mjoin.TwoPhaseJoin"/>
<algorithm-identifier id="31" mode="common" name="dblab.common.job.join.HalfJoinPlus"/>
<algorithm-identifier id="32" mode="common" name="dblab.dsmm.job.estDec.EstMax"/>
<algorithm-identifier id="33" mode="common" name="dblab.common.job.period.Period"/>
<algorithm-identifier id="34" mode="common" name="dblab.dsmm.job.oneitemfrequent.OneItemFrequent"/>
<algorithm-identifier id="35" mode="common" name="dblab.dsmm.job.socketoutput.SocketOutput"/>
<algorithm-identifier id="36" mode="mining" name="dblab.dsmm.job.ctx.Context"/>
<algorithm-identifier id="1001" mode="common" name="dblab.common.job.join.KospiIndex"/>
</algorithm-definition>


</task-list>
